events { worker_connections 1024; }

http {
    server {
        listen 8080;

        location /api/startups {
            proxy_pass http://startups_service:3001;
        }

        location /api/technologies {
            proxy_pass http://technologies_service:3002;
        }
    }
}
